### ISSUE TITLE
animation running throw exception

### ISSUE THREAD

**Issue by NemoChen317** [omerbyrk/add_to_cart_animation#2]
when i runAddToCartAnimation throw Exception

E/flutter (16483): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (16483): #0      _AddToCartAnimationState.runAddToCardAnimation (package:add_to_cart_animation/add_to_cart_animation.dart:173:42)
E/flutter (16483): <asynchronous suspension>

**Comment by omerbyrk** [comment]
How can I reproduce the error?
