### ISSUE TITLE
Problem with ticker dispose

### ISSUE THREAD

**Issue by WGFizban** [omerbyrk/add_to_cart_animation#4]
I use add_to_cart_animation in my project. When I go back from screen whree i used it to my second screen after correct dispose my screen I see error in debug console:

Exception has occurred.
FlutterError (CartIconKey#36ff4(ticker active but muted) was disposed with an active Ticker.
CartIconKey created a Ticker via its SingleTickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before calling super.dispose().
Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.
The offending ticker was:
  Ticker(created by CartIconKey#36ff4)

version: 2.0.1

Fix for that is easy. Please change order this two function. I create special PR for that isuue.
![image](https://user-images.githubusercontent.com/63311150/210797833-0d2db224-3e8d-4d4a-8f6d-bbba91cfdf48.png)

**Comment by omerbyrk** [comment]
Thank you.
