### ISSUE TITLE
Animation Exception Error

### ISSUE THREAD

**Issue by padit69** [omerbyrk/add_to_cart_animation#9]
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
setState() called after dispose(): _AnimationActionSheetSelectSericeState#60076(lifecycle state: defunct)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

***
My step:
Step1: Using bottom sheet view have using lib.
Step2: Action tap to many item.
Step3: Don't waiting animation end. I close bottom sheet.
Step4: Error show it

**Comment by omerbyrk** [comment]
That's normal because you are killing the widgets what animation depends on.

**Comment by muthukrishnanOCS** [comment]
@omerbyrk Can you please add the condition like this and give new update for the package ? Because the exception also reported in crashlytics
Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
